%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Next Generation Sequencing QC Report
%
% Original authors:
% Tobias Meissner
%
% License:
% MIT
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%----------------------------------------------------------------------------------------
%  Data Input
%----------------------------------------------------------------------------------------

<<r init, echo=FALSE>>=
library(knitr)
library(xtable)
library(XML)
source('BaseSpaceRunInfo.R')

sanitizeLatexS <- function(str) {
    gsub('([#$%&~_\\^\\\\{}])', '\\\\\\\\\\1', str, perl = TRUE);
}
@

<<dataIn, echo=FALSE>>=
## FASTQC
fastqc1 <- read.csv2(unz(fastqc1File, paste(sampleID,'_1_fastqc/summary.txt',sep='')), sep='\t', header=F)
fastqc2 <- read.csv2(unz(fastqc2File, paste(sampleID,'_2_fastqc/summary.txt',sep='')), sep='\t', header=F)
colnames(fastqc1) <- c('Result', 'Analysis', 'File')
colnames(fastqc2) <- c('Result', 'Analysis', 'File')

parseCoverage <- function(coverage) {
  paste0(gsub("%", "", strsplit(as.character(coverage), " ")[[1]][9]), "%")
}

q <- read.csv(qualimapText, sep="\t")
qh <- readHTMLTable(qualimapHTML, header=TRUE)
qualimapStats <- list(
    `Total Reads` = as.numeric(gsub(",", "", strsplit(as.character(q[10,]), " = ")[[1]][2])),
    `Duplication Rate` = paste0(as.character(round(100*(as.numeric(gsub(",", "", strsplit(as.character(q[15,]), " = ")[[1]][2]))/as.numeric(gsub(",", "", strsplit(as.character(q[10,]), " = ")[[1]][2])))), 2), "%"),
    `Mapped reads, both in pair` = strsplit(as.character(qh[[4]][7,][[2]]), " / ")[[1]][2],
    `Mapped reads, both in pair, inside of regions` = strsplit(as.character(qh[[5]][4,][[2]]), " / ")[[1]][2],
    `GC Content` = strsplit(as.character(q[28,]), " = ")[[1]][2],
    `Median Insert Size` = strsplit(as.character(q[19,]), " = ")[[1]][2],
    `Mean Coverage` = paste0(gsub("X", "", strsplit(as.character(q[38,]), " = ")[[1]][2]), "X"),
    `StdDev Coverage` = paste0(gsub("X", "", strsplit(as.character(q[39,]), " = ")[[1]][2]), "X"),
    `1X` = parseCoverage(q[40,]),
    `10X` = parseCoverage(q[49,]),
    `20X` = parseCoverage(q[59,]),
    `50X` = parseCoverage(q[89,]))
@

%----------------------------------------------------------------------------------------
%  Sample Information
%----------------------------------------------------------------------------------------

<<sampleinfo, echo=FALSE>>=

@

\PassOptionsToPackage{table}{xcolor}
\documentclass[11pt, stdletter, dateno]{newlfm}
\usepackage{xcolor}
\usepackage{tabularx}
\usepackage{longtable}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{wallpaper}
\usepackage{array}

%% styling
\newcolumntype{x}[1]{>{\centering\arraybackslash\hspace{0pt}}p{#1}} % centered with column 
\newlfmP{noheadline,noHeadline}
%\leftmarginsize{0in}
%\rightmarginsize{0in}
%\topmarginsize{2mm}
%\topmarginskip{0in}
%\headermarginsize{0cm}
%\headermarginskip{0in}

%% header
\unprtop{0.65cm}
\Rheader{\parbox{\textwith}{\small{\begin{tabbing} \textbf{Patient Name} \hspace*{1.25cm} \= \textbf{Report Date} \hspace*{0.75cm} \= \textbf{Tumor Type} \\ \Sexpr{sample$patient$name}, \Sexpr{sample$patient$surname} \> \today \> \Sexpr{sample$patient$tumor_type} \end{tabbing}}}}
%% footer
\unprbottom{1.4cm}
\Lfooter{\scriptsize{Electronically Signed by \Sexpr{sample$medical_director$surname} \Sexpr{sample$medical_director$name} \Sexpr{sample$medical_director$title} | CLIA Number: \Sexpr{sample$lab$clia_number} | \today \\ \Sexpr{sample$lab$name}, \Sexpr{sample$lab$street}, \Sexpr{sample$lab$city}, \Sexpr{sample$lab$state}, \Sexpr{sample$lab$zip}  \hfill page \thepage}} 
\lfooter{\scriptsize{Electronically Signed by \Sexpr{sample$medical_director$surname} \Sexpr{sample$medical_director$name} \Sexpr{sample$medical_director$title} | CLIA Number: \Sexpr{sample$lab$clia_number} | \today \\ \Sexpr{sample$lab$name}, \Sexpr{sample$lab$street}, \Sexpr{sample$lab$city}, \Sexpr{sample$lab$state}, \Sexpr{sample$lab$zip}  \hfill page \thepage}} 

%% add section support 
\newcounter{section}
\newcounter{subsection}[section]
\newcounter{subsubsection}[section]
\setcounter{secnumdepth}{4}
\makeatletter
\renewcommand\section{\@startsection{section}{1}{\z@}%
                                   {-3.5ex \@plus -1ex \@minus -.2ex}%
                                   {2.3ex \@plus.2ex}%
                                   {\normalfont\normalsize\bfseries}}
\newcommand\subsection{\@startsection{subsection}{2}{\z@}%
                                     {-3.25ex\@plus -1ex \@minus -.2ex}%
                                     {1.5ex \@plus .2ex}%
                                     {\normalfont\normalsize\bfseries}}
\newcommand\subsubsection{\@startsection{subsubsection}{3}{\z@}%
                                     {-3ex\@plus -1ex \@minus -.2ex}%
                                     {0.7ex \@plus .2ex}%
                                     {\normalfont\normalsize\bfseries}}                                     
\renewcommand\thesection{\@arabic\c@section}
\renewcommand\thesubsection{\thesection.\@arabic\c@subsection}
\renewcommand\thesubsubsection{\thesubsubsection.\@arabic\c@subsubsection}
\makeatother

%----------------------------------------------------------------------------------------
%  ADDRESSEE SECTION
%----------------------------------------------------------------------------------------
%\nameto{\Sexpr{sample$physician_addr$surname} \Sexpr{sample$physician_addr$name}} 
%\addrto{\parbox{3in}{\Sexpr{sample$physician_addr$street} \\ \Sexpr{sample$physician_addr$city}, \Sexpr{sample$physician_addr$state}, \Sexpr{sample$physician_addr$zip}}}
                   
%----------------------------------------------------------------------------------------
%  YOUR NAME & ADDRESS SECTION
%----------------------------------------------------------------------------------------                     
%% addres send from
%\namefrom{Sherlock Holmes} 
%\addrfrom{\parbox{2in}{221B Baker Street \\ London, UK}}

%\greetto{}

%----------------------------------------------------------------------------------------
%  Start Document
%----------------------------------------------------------------------------------------

\begin{document}
\SweaveOpts{concordance=TRUE}

\begin{newlfm}

%\ThisCenterWallPaper{1}{avera_letter.pdf}
\CenterWallPaper{1}{avera_letter.pdf}

%----------------------------------------------------------------------------------------
%	Content
%----------------------------------------------------------------------------------------

\vspace*{-4.25cm}
\textbf{DNA-Seq QC Report for Sample \Sexpr{sanitizeLatexS(patID)}}

\vspace*{-0.5cm}
\line(1,0){475}  

%% SAMPLE INFORMATION

\vspace{-0.3cm}
\begin{scriptsize}
\begin{tabbing}
\textbf{Date of birth:} \= \Sexpr{sample$patient$date_of_birth} \hspace{0.7cm}  \= \textbf{Medical Facility:} \hspace{0.4cm} \= \Sexpr{sample$physician$facility} \hspace{0.4cm} \= \textbf{Specimen Received:} \= \Sexpr{sample$sample_details$received} \\ 
\textbf{Sex:} \>\Sexpr{sample$patient$sex} \> \textbf{Ordering Physician:} \> \Sexpr{sample$physician$name}, \Sexpr{sample$physician$surname} \> \textbf{Specimen Site:} \> \Sexpr{sample$patient$tumor_site} \\
\textbf{Specimen ID:} \>\Sexpr{sample$patient$specimen_id} \> \textbf{Medical Facility ID:} \> \Sexpr{sample$physician$facility_id} \> \textbf{Date of Collection:} \> \Sexpr{sample$sample_details$biopsy_date} \\
\> \> \textbf{Pathologist:} \> \Sexpr{sample$pathologist$name}, \Sexpr{sample$pathologist$surname} \> \textbf{Specimen Type:} \> \Sexpr{sample$patient$specimen_type}
\end{tabbing}
\end{scriptsize}
\vspace{-0.6cm}
\line(1,0){475}

%% Run Info

<<runinfo,results=hide,echo=FALSE>>=
runSummary <- lapply(sample$run_info$run_id, getRunSummary, accessToken)
runSummarySample <- sapply(runSummary, function(x) {
  #ind <- grep(sampleID, x$Sample)
  ind <- grep('054-T1-DNA', x$Sample)
  x[ind, ]
})

# how many runs for this sample
nSample <- apply(runSummarySample, 2, function(x) {
  ifelse(length(x$Sample)==1, TRUE, FALSE)
})
runSummarySample <- runSummarySample[,nSample]

total_yield_gb <- sapply(runSummary[nSample], function(x) {
  round((sum(x$`Total Reads`)-x$`Total Reads`[grep('Undetermined', x$Sample)])*300/1000000000,2)
})
percent_q_score_30 <- apply(runSummarySample, 2, function(x) {
  round(x$`Percent Q30`,2)
})
percent_phix_alg <- apply(runSummarySample, 2, function(x) {
  round(x$`Percent Aligned`,2)
})
phix_error_rate <- apply(runSummarySample, 2, function(x) {
  round(x$`Error Rate`,2)
})
run_id <- apply(runSummarySample, 2, function(x) {
  round(x$`Run Id`,2)
})

runinfoGB <- ifelse(total_yield_gb>=90, "$\\text{\\color{red}{\\rlap{$\\checkmark$}}}\\square$", "$\\square$")
runinfoQ30 <- ifelse(percent_q_score_30>=75, "$\\text{\\color{red}{\\rlap{$\\checkmark$}}}\\square$", "$\\square$")
runinfoPhiX <- ifelse(percent_phix_alg>=0.05, "$\\text{\\color{red}{\\rlap{$\\checkmark$}}}\\square$", "$\\square$")
runinfoPhiXErr <- ifelse(phix_error_rate<2.5, "$\\text{\\color{red}{\\rlap{$\\checkmark$}}}\\square$", "$\\square$")
@

<<runinfo_table,results=tex,echo=FALSE>>=
for (i in 1:length(which(nSample))) {
  cat("\\vspace*{-0.6cm}\n")
  cat(paste0("\\section*{Run Info ",i,"}\n"))
  cat("\\vspace*{-0.5cm}\n")
  cat("\\begin{tabularx}{\\textwidth}{ p{5.5cm} p{3.5cm} p{3.5cm} x{2cm} } \\hline\n")
  cat("Metric: & Value & Expected & QCPassed \\tabularnewline \\hline\n")
  cat(paste0("Run ID: & \\Sexpr{",run_id[i],"} & & \\tabularnewline\n"))
  cat(paste0("Seq-Type: &  \\multicolumn{3}{l}{\\Sexpr{",sample$sample_details$seq_type[nSample][i],"}} \\tabularnewline\n"))
  cat(paste0("Seq-Protocoll: & \\multicolumn{3}{l}{\\Sexpr{",sample$sample_details$seq_protocoll[nSample][i],"}} \\tabularnewline\n"))
  cat(paste0("Total Yield: &  \\Sexpr{",total_yield_gb[i],"} (GB) & 90 - 120 (GB) & \\Sexpr{",runinfoGB[i],"} \\tabularnewline\n"))
  cat(paste0("Q30: &  \\Sexpr{",percent_q_score_30[i],"} (\\%) & > 75 (\\%) & \\Sexpr{",runinfoQ30[i],"} \\tabularnewline\n"))
  cat(paste0("PhiX aligned: &  \\Sexpr{",percent_phix_alg[i],"} (\\%) & > 0.05 (\\%) & \\Sexpr{",runinfoPhiX[i],"} \\tabularnewline\n"))
  cat(paste0("PhiX error: &  \\Sexpr{",phix_error_rate[i],"} (\\%) & < 2.5 (\\%) & \\Sexpr{",runinfoPhiXErr[i],"}\n"))
  cat("\\end{tabularx}\n\n")
}
@

%% Sample Sequencing Info

<<seqinfo, results=hide, echo=FALSE>>=
totalReadsSample <- round(sum(unlist(runSummarySample[1,]))/1000000,2)
seqinfoTotalReads <- ifelse(totalReadsSample>=200, "$\\\\text{\\\\color{red}{\\\\rlap{$\\\\checkmark$}}}\\\\square$", "$\\\\square$")
seqinfoInsert <- ifelse(qualimapStats$`Median Insert Size`>=175 & qualimapStats$`Median Insert Size`<=350, "$\\\\text{\\\\color{red}{\\\\rlap{$\\\\checkmark$}}}\\\\square$", "$\\\\square$")
@

\vspace*{-0.4cm}
\section*{Sample Sequencing Info}
\vspace*{-0.5cm}
\begin{tabularx}{\textwidth}{  p{5.5cm} p{3.5cm} p{3.5cm} x{2cm} } \hline
Metric: & Value & Expected & QCPassed \tabularnewline \hline

<<seqinfo_table, results=tex, echo=FALSE>>=
for (i in 1:length(which(nSample))) {
  cat(paste0("Number of Reads Run ",i,": &  \\Sexpr{",round(unlist(runSummarySample[1,])[i]/1000000,2),"} (mio) &  &  \\tabularnewline\n"))
}
@

Total Reads: & \Sexpr{totalReadsSample} (mio) & 200 (mio) & \Sexpr{seqinfoTotalReads} \tabularnewline
Insert Size: & \Sexpr{qualimapStats$`Median Insert Size`} (bp) & 175 - 350 (bp) & \Sexpr{seqinfoInsert}
\end{tabularx}

%% Sample Mapping Info

\vspace*{-0.4cm}
\section*{Sample Mapping Info}
\vspace*{-0.5cm}
<<samplemapping, echo=FALSE, results=tex>>=
mappingTable <- data.frame(
                      Metric=c('Total reads',
                               'Duplication rate',
                               'Mapped reads',
                               'Mapped reads inside of regions',
                               'Mean Coverage',
                               'Coverage 1x',
                               'Coverage 10x',
                               'Coverage 20x',
                               'Coverage 50x',
                               'GC Content'
                               
                      ),
                      Value=c(round(qualimapStats$`Total Reads`/1000000,2),
                              gsub('%',' (\\\\%)',qualimapStats$`Duplication Rate`),
                              gsub('%',' (\\\\%)',qualimapStats$`Mapped reads, both in pair`),
                              gsub('%',' (\\\\%)',qualimapStats$`Mapped reads, both in pair, inside of regions`),
                              qualimapStats$`Mean Coverage`,
                              gsub('%',' (\\\\%)',qualimapStats$`1X`),
                              gsub('%',' (\\\\%)',qualimapStats$`10X`),
                              gsub('%',' (\\\\%)',qualimapStats$`20X`),
                              gsub('%',' (\\\\%)',qualimapStats$`50X`),
                              gsub('%',' (\\\\%)',qualimapStats$`GC Content`)
                      ),                      
                      Expected=c('> 200 (mio)',
                                 '< 50 (\\%)',
                                 '> 95 (\\%)',
                                 '> 75 (\\%)',
                                 '> 75X',
                                 '> 99 (\\%)',
                                 '> 97 (\\%)',
                                 '> 95 (\\%)',
                                 '> 85 (\\%)',
                                 '< 52 (\\%)'
                      ),
                      QCPassed=NA
                      )

# check if qc passed
mappingTable$QCPassed[1] <- ifelse(qualimapStats$`Total Reads`>=200000000, "$\\text{\\color{red}{\\rlap{$\\checkmark$}}}\\square$", "$\\square$")
mappingTable$QCPassed[2] <- ifelse(as.numeric(gsub('%','',qualimapStats$`Duplication Rate`))<=50, "$\\text{\\color{red}{\\rlap{$\\checkmark$}}}\\square$", "$\\square$")
mappingTable$QCPassed[3] <- ifelse(as.numeric(gsub('%','',qualimapStats$`Mapped reads, both in pair`))>=95, "$\\text{\\color{red}{\\rlap{$\\checkmark$}}}\\square$", "$\\square$")  
mappingTable$QCPassed[4] <- ifelse(as.numeric(gsub('%','',qualimapStats$`Mapped reads, both in pair, inside of regions`))>=75, "$\\text{\\color{red}{\\rlap{$\\checkmark$}}}\\square$", "$\\square$")  
mappingTable$QCPassed[5] <- ifelse(as.numeric(gsub('X','',qualimapStats$`Mean Coverage`))>=75, "$\\text{\\color{red}{\\rlap{$\\checkmark$}}}\\square$", "$\\square$")    
mappingTable$QCPassed[6] <- ifelse(as.numeric(gsub('%','',qualimapStats$`1X`))>=99, "$\\text{\\color{red}{\\rlap{$\\checkmark$}}}\\square$", "$\\square$")  
mappingTable$QCPassed[7] <- ifelse(as.numeric(gsub('%','',qualimapStats$`10X`))>=97, "$\\text{\\color{red}{\\rlap{$\\checkmark$}}}\\square$", "$\\square$")  
mappingTable$QCPassed[8] <- ifelse(as.numeric(gsub('%','',qualimapStats$`20X`))>=95, "$\\text{\\color{red}{\\rlap{$\\checkmark$}}}\\square$", "$\\square$")  
mappingTable$QCPassed[9] <- ifelse(as.numeric(gsub('%','',qualimapStats$`50X`))>=85, "$\\text{\\color{red}{\\rlap{$\\checkmark$}}}\\square$", "$\\square$")  
mappingTable$QCPassed[10] <- ifelse(as.numeric(gsub('%','',qualimapStats$`GC Content`))<52, "$\\text{\\color{red}{\\rlap{$\\checkmark$}}}\\square$", "$\\square$")  

mapping.Table <- xtable(mappingTable)
align(mapping.Table) <- "lp{5.5cm}p{3.5cm}p{3.5cm}x{2cm}"
print(mapping.Table,
      #align=c("c","c","c","c","c"),
      include.rownames=FALSE,
      type='latex',
      sanitize.text.function = function(x) x,
      latex.environments = "left",
      tabular.environment="tabularx",
      width="\\textwidth",
      hline.after = c(-1,0)
      )
@

% Variant Calling Info

<<snpinfo, results=hide, echo=FALSE>>=
#snpinfoPanel <- "$\\\\square$" #ifelse(   >=90, "$\\\\text{\\\\color{red}{\\\\rlap{$\\\\checkmark$}}}\\\\square$", "$\\\\square$")
@


%\vspace*{-0.35cm}
%\section*{Sample Variant Calling Info}
%\vspace*{-0.5cm}
%\begin{tabularx}{\textwidth}{  p{5.5cm} p{3.5cm} p{3.5cm} x{2cm} } \hline
%Metric: & Value & Expected & QCPassed \tabularnewline \hline
%SNP Panel Callable & \Sexpr{round((callableN/callableTotal)*100,1)} (\%) & > 90 (\%) & \Sexpr{print(snpinfoPanel)}
%\end{tabularx}

% begin of page 2 ...
\clearpage

\section*{Softwareversions and Parameters}

\begin{tabbing}
Reference Genome - Human (UCSC hg19) \= STAR Version 2.xx \\
FastQC xyz \> Samtools 1.19.xx \\
Picard xyz
\end{tabbing}

%\section*{Session Info}
%
%<<sessioninfo, echo=FALSE>>=
%sessionInfo()
%@

%----------------------------------------------------------------------------------------

\end{newlfm}

\end{document}